language: node_js
os: linux
dist: xenial
node_js: "12"

addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d $HOME/bin

install:
  - export PATH=$HOME:$PATH
  - yarn init -y
  - yarn add selenium-stealth
